// F6: NPS auto-send cron — runs daily at 10:00 UTC
// Finds cases closed/converted in last 24h and sends NPS survey via Telegram + email
export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import { q, one } from "@/lib/db";
import { sendMessage } from "@/lib/telegram";
import { sendEmail, npsSurveyEmailHtml } from "@/lib/email";

const SITE = process.env.NEXT_PUBLIC_APP_URL || "https://kompasmigracji.com";

function checkCronAuth(req: NextRequest): boolean {
  const cronHeader = req.headers.get("x-vercel-cron");
  const authHeader = req.headers.get("authorization");
  const secret = process.env.CRON_SECRET;
  return cronHeader === "1" || (!!secret && authHeader === `Bearer ${secret}`);
}

export async function POST(req: NextRequest) {
  if (!checkCronAuth(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Find leads closed/converted (recently or unsurveyed) that don't have an NPS survey yet
  // Note: leads table has no updated_at; use paid_at or created_at as proxy
  const closedLeads = await q(
    `SELECT l.id, l.first_name, l.contact, l.chat_id
     FROM leads l
     WHERE l.status IN ('closed','converted')
       AND l.deleted_at IS NULL
       AND NOT EXISTS (
         SELECT 1 FROM kompas_nps_surveys ns WHERE ns.lead_id = l.id
       )
     ORDER BY l.created_at DESC
     LIMIT 20`,
  );

  let sent = 0;
  for (const lead of closedLeads) {
    const name = lead.first_name || "Drogi Kliencie";

    // Insert NPS survey row (token auto-generated by DB DEFAULT)
    const surveyRow = await one(
      `INSERT INTO kompas_nps_surveys (lead_id, client_name, sent_at)
       VALUES ($1,$2,now()) RETURNING token`,
      [lead.id, name],
    );
    if (!surveyRow?.token) continue;

    const surveyUrl = `${SITE}/nps?token=${surveyRow.token}`;

    // Send Telegram if client has chat_id
    if (lead.chat_id) {
      await sendMessage(
        lead.chat_id,
        `Dziekujemy za wspolprace, ${name}! &#x1F917;\n\n` +
        `Twoja sprawa zostala zamknieta. Bedziemy wdzieczni za krotka opinie — ` +
        `pomoze nam to lepiej Ci sluzyc:\n\n${surveyUrl}`,
        "HTML",
      ).catch(() => {});
      sent++;
    }

    // Send email if contact looks like email
    const contact = String(lead.contact || "");
    if (contact.includes("@")) {
      await sendEmail(
        contact,
        "Jak oceniasz nasze uslugi? — Kompas Migracji",
        npsSurveyEmailHtml(name, surveyRow.token),
        "nps_survey",
      ).catch(() => {});
      sent++;
    }
  }

  return NextResponse.json({ ok: true, surveysCreated: closedLeads.length, notificationsSent: sent });
}

export async function GET(req: NextRequest) {
  return POST(req);
}
