/* KompasCRM — роли, права, навигация. */

export const ROLE_LABEL = {
  admin: "Адміністратор",
  moderator: "Модератор",
  member: "Учасник профспілки",
};

/* Пункти меню. Кожен видно тільки вказаним ролям. */
export const NAV = [
  { href: "/admin",                 label: "Дашборд",             icon: "grid",     roles: ["admin", "moderator"] },
  { href: "/admin/analytics",       label: "Аналітика & Звіти",   icon: "pie-chart",roles: ["admin", "manager"] },
  { href: "/admin/accounting",      label: "Бухгалтерія & Payroll",icon: "dollar-sign",roles: ["admin"] },
  { href: "/admin/franchise",       label: "Мережа Франшиз",      icon: "map",      roles: ["admin"] },
  { href: "/admin/marketing",       label: "Email Маркетинг",     icon: "send",     roles: ["admin", "manager", "marketing"] },
  { href: "/admin/hr",              label: "Команда & HR",        icon: "users",    roles: ["admin", "manager"] },
  { href: "/admin/doc-builder",     label: "Генератор Документів",icon: "file-plus",roles: ["admin", "manager", "lawyer"] },
  { href: "/admin/booking",         label: "Візити (E-Kolejka)",  icon: "calendar", roles: ["admin", "manager", "sales", "lawyer", "support"] },
  { href: "/admin/e-invoicing",     label: "KSeF Фактури",        icon: "file-text",roles: ["admin", "manager", "accountant"] },
  { href: "/admin/gov-integration", label: "RPA Боти (ZUS/Urząd)",icon: "cpu",      roles: ["admin", "manager"] },
  { href: "/admin/client-portal",   label: "Клієнтський Портал",  icon: "layout",   roles: ["admin", "manager", "support"] },
  { href: "/admin/knowledge-base",  label: "База Знань (Wiki)",   icon: "book-open", roles: ["admin", "manager", "lawyer", "sales", "support"] },
  { href: "/admin/partners",        label: "B2B Партнери",        icon: "users",    roles: ["admin", "manager", "sales"] },
  { href: "/admin/feedback",        label: "Відгуки (NPS)",       icon: "star",     roles: ["admin", "manager", "support", "marketing"] },
  { href: "/admin/subscriptions",   label: "Підписки (MRR)",      icon: "refresh-cw", roles: ["admin", "manager", "sales"] },
  { href: "/admin/chat",            label: "Чат Команди",         icon: "message-circle", roles: ["admin", "manager", "sales", "lawyer", "support", "marketing"] },
  { href: "/admin/translations",    label: "Присяжні Переклади",  icon: "globe",    roles: ["admin", "manager", "lawyer", "support"] },
  { href: "/admin/leaderboard",     label: "Рейтинг Sales",       icon: "award",    roles: ["admin", "manager", "sales"] },
  { href: "/admin/events",          label: "Івенти & Вебінари",   icon: "calendar", roles: ["admin", "manager", "marketing"] },
  { href: "/admin/integrations",    label: "API & Інтеграції",    icon: "link",     roles: ["admin"] },
  { href: "/admin/lms",             label: "Академія (LMS)",      icon: "book",     roles: ["admin", "manager", "sales", "lawyer", "support"] },
  { href: "/admin/call-center",     label: "Колл-Центр (VoIP)",   icon: "phone-call",roles: ["admin", "manager", "sales", "support"] },
  { href: "/admin/e-signatures",    label: "Електронні Підписи",  icon: "edit-3",   roles: ["admin", "manager", "lawyer", "sales"] },
  { href: "/admin/hr-leave",        label: "Відпустки (HR)",      icon: "calendar", roles: ["admin", "manager", "sales", "lawyer", "support"] },
  { href: "/admin/expenses",        label: "Витрати & P&L",       icon: "dollar-sign", roles: ["admin"] },
  { href: "/admin/ocr-scanner",     label: "AI Скан Документів",  icon: "maximize", roles: ["admin", "manager", "lawyer", "support"] },
  { href: "/admin/affiliates",      label: "Промокоди & Блогери", icon: "tag",      roles: ["admin", "marketing"] },
  { href: "/admin/email-sequences", label: "Email Воронки",       icon: "git-commit",roles: ["admin", "manager", "marketing"] },
  { href: "/admin/partner-portal",  label: "Партнери (B2B)",      icon: "users",    roles: ["admin", "manager"] },
  { href: "/admin/sla",             label: "Контроль Дедлайнів",  icon: "flag",     roles: ["admin", "manager", "lawyer"] },
  { href: "/admin/service-catalog", label: "Каталог Послуг",      icon: "shopping-bag",roles: ["admin", "manager", "sales"] },
  { href: "/admin/branches",        label: "Мережа Філій",        icon: "map",      roles: ["admin"] },
  { href: "/admin/goals",           label: "Цілі та OKR",         icon: "target",   roles: ["admin", "manager"] },
  { href: "/admin/relationships",   label: "Карта Зв'язків",      icon: "share-2",  roles: ["admin", "manager", "sales"] },
  { href: "/admin/time-tracking",   label: "Облік Часу",          icon: "clock",    roles: ["admin", "lawyer", "manager"] },
  { href: "/admin/playbooks",       label: "Скрипти Продажів",    icon: "book-open",roles: ["admin", "manager", "sales"] },
  { href: "/admin/team-chat",       label: "Командний Чат",       icon: "hash",     roles: ["admin", "manager", "support", "lawyer", "sales"] },
  { href: "/admin/data-import",     label: "Імпорт & Експорт",    icon: "download-cloud",roles: ["admin"] },
  { href: "/admin/help-center",     label: "База Знань (FAQ)",    icon: "book-open",roles: ["admin", "manager", "support"] },
  { href: "/admin/currencies",      label: "Курси Валют",         icon: "dollar-sign", roles: ["admin", "accountant"] },
  { href: "/admin/lead-routing",    label: "Розподіл Лідів",      icon: "git-merge",roles: ["admin", "manager"] },
  { href: "/admin/gamification",    label: "Гейміфікація",        icon: "award",    roles: ["admin", "manager", "sales"] },
  { href: "/admin/mobile-app",      label: "Мобільний Додаток",   icon: "smartphone",roles: ["admin"] },
  { href: "/admin/permissions",     label: "Ролі та Доступи",     icon: "key",      roles: ["admin"] },
  { href: "/admin/ocr",             label: "AI Розпізнавання",    icon: "file-text",roles: ["admin", "manager", "lawyer"] },
  { href: "/admin/custom-fields",   label: "Кастомні Поля",       icon: "tag",      roles: ["admin"] },
  { href: "/admin/audit-log",       label: "Журнал Безпеки",      icon: "shield",   roles: ["admin"] },
  { href: "/admin/localization",    label: "Переклади (Мови)",    icon: "globe",    roles: ["admin", "manager"] },
  { href: "/admin/copilot",         label: "AI Асистент",         icon: "cpu",      roles: ["admin", "manager", "sales", "lawyer"] },
  { href: "/admin/booking",         label: "Календар & Зустрічі", icon: "calendar", roles: ["admin", "manager", "sales", "lawyer"] },
  { href: "/admin/livechat",        label: "Live Chat (Inbox)",   icon: "message-circle", roles: ["admin", "manager", "support"] },
  { href: "/admin/customer-success",label: "Customer Success",    icon: "heart",    roles: ["admin", "manager", "sales"] },
  { href: "/admin/data-room",       label: "Data Room (Сейф)",    icon: "shield",   roles: ["admin", "manager", "lawyer"] },
  { href: "/admin/academy",      label: "Навчання (Академія)", icon: "play-circle",roles: ["admin", "manager", "user"] },
  { href: "/admin/timesheets",   label: "Облік Часу (Таймер)", icon: "clock",    roles: ["admin", "manager", "lawyer"] },
  { href: "/admin/campaigns",    label: "Email Розсилки",      icon: "mail",     roles: ["admin", "manager", "marketing"] },
  { href: "/admin/workflows",    label: "Автоматизація",       icon: "git-merge",roles: ["admin", "manager"] },
  { href: "/admin/partners",     label: "B2B Партнери",        icon: "users",    roles: ["admin", "manager"] },
  { href: "/admin/integrations", label: "Інтеграції & API",    icon: "layers",   roles: ["admin", "manager"] },
  { href: "/admin/commissions",  label: "Комісійні та Бонуси", icon: "dollar-sign",roles: ["admin", "manager", "sales"] },
  { href: "/admin/products",     label: "Каталог Послуг",      icon: "package",  roles: ["admin", "manager", "sales"] },
  { href: "/admin/projects",     label: "Проекти & Задачі",    icon: "trello",   roles: ["admin", "manager", "user"] },
  { href: "/admin/loyalty",      label: "Лояльність & Бонуси", icon: "award",    roles: ["admin", "manager", "sales"] },
  { href: "/admin/leads-finder", label: "Пошук B2B Лідів",     icon: "search",   roles: ["admin", "manager", "sales"] },
  { href: "/admin/contracts",    label: "Договори & Підписи",  icon: "file-text",roles: ["admin", "manager", "lawyer"] },
  { href: "/admin/calls",        label: "Телефонія & Дзвінки", icon: "phone",    roles: ["admin", "manager", "sales"] },
  { href: "/admin/reviews",      label: "Відгуки & Репутація", icon: "star",     roles: ["admin", "manager", "support"] },
  { href: "/admin/subscriptions",label: "Підписки & MRR",      icon: "credit-card",roles: ["admin", "manager"] },
  { href: "/admin/forms",        label: "Форми & Опитування",  icon: "check-square",roles: ["admin", "manager"] },
  { href: "/admin/wiki",         label: "База Знань (Wiki)",   icon: "book",     roles: ["admin", "manager", "user"] },
  { href: "/admin/social",       label: "Соцмережі & SMM",     icon: "instagram",roles: ["admin", "manager"] },
  { href: "/admin/goals",        label: "Цілі & OKR",          icon: "target",   roles: ["admin", "manager"] },
  { href: "/admin/assets",       label: "Майно та IT-техніка", icon: "laptop",   roles: ["admin", "manager"] },
  { href: "/admin/expenses",     label: "Витрати & Чеки",      icon: "credit-card",roles: ["admin", "manager"] },
  { href: "/admin/fleet",        label: "Автопарк & Рейси",    icon: "truck",    roles: ["admin", "manager", "driver"] },
  { href: "/admin/legal",        label: "Юридичні Справи",     icon: "briefcase",roles: ["admin", "manager", "lawyer"] },
  { href: "/admin/recruitment",  label: "Рекрутинг & Найм",    icon: "briefcase",roles: ["admin", "manager"] },
  { href: "/admin/housing",      label: "Житло & Оренда",      icon: "home",     roles: ["admin", "manager"] },
  { href: "/admin/transcripts",  label: "AI Аналіз Дзвінків",  icon: "mic",      roles: ["admin", "manager"] },
  { href: "/admin/invoices",     label: "Рахунки & Оплата",    icon: "dollar-sign", roles: ["admin", "manager"] },
  { href: "/admin/monitoring",   label: "Статус Системи",      icon: "activity", roles: ["admin", "developer"] },
  { href: "/admin/cms",          label: "Сайт & Блог (CMS)",   icon: "layout",   roles: ["admin", "manager", "editor"] },
  { href: "/admin/partners",     label: "Партнери & Афіліати", icon: "link",     roles: ["admin", "manager"] },
  { href: "/admin/marketing",    label: "Маркетинг & Email",   icon: "mail",     roles: ["admin", "manager"] },
  { href: "/admin/hr",           label: "Команда & HR",        icon: "users",    roles: ["admin", "manager"] },
  { href: "/admin/ai-training",  label: "Навчання ШІ",         icon: "cpu",      roles: ["admin", "manager"] },
  { href: "/admin/members",      label: "Учасники профспiлки", icon: "users",    roles: ["admin", "moderator"] },
  { href: "/admin/tasks",          label: "Задачі & Проекти",    icon: "check",    roles: ["admin", "manager", "user"] },
  { href: "/admin/issues",         label: "Баг-трекер",          icon: "alert-triangle", roles: ["admin", "developer", "manager"] },
  { href: "/admin/lms",            label: "Академія & Курси",    icon: "book-open",roles: ["admin", "manager"] },
  { href: "/admin/inventory",      label: "Товари & Склад",      icon: "box",      roles: ["admin", "manager"] },
  { href: "/admin/documents",      label: "Документи & Підписи", icon: "file-text",roles: ["admin", "manager", "user"] },
  { href: "/admin/forms",          label: "Форми & Опитування",  icon: "layout",   roles: ["admin", "manager"] },
  { href: "/admin/tickets",        label: "Служба Підтримки",    icon: "message-square", roles: ["admin", "manager"] },
  { href: "/admin/knowledge-base", label: "База Знань & FAQ",    icon: "book-open", roles: ["admin", "manager", "user"] },
  { href: "/admin/calls",          label: "Кол-центр",           icon: "phone",    roles: ["admin", "manager", "user"] },
  { href: "/admin/gamification",   label: "Гейміфікація",        icon: "award",    roles: ["admin", "manager", "user"] },
  { href: "/admin/cases",          label: "Справи клієнтів",     icon: "folder",   roles: ["admin", "manager", "user"] },
  { href: "/admin/workers",      label: "Канбан",              icon: "clipboard", roles: ["admin", "moderator"] },
  { href: "/admin/templates",    label: "Шаблони",             icon: "layers",   roles: ["admin", "moderator"] },
  { href: "/admin/broadcasts",     label: "Розсилки",            icon: "send",       roles: ["admin"] },
  { href: "/admin/referrals",      label: "Реферали",            icon: "link",       roles: ["admin"] },
  { href: "/admin/revenue",        label: "Доходи & MRR",        icon: "cash",       roles: ["admin"] },
  { href: "/admin/subscriptions",  label: "Підписки",            icon: "refresh",    roles: ["admin"] },
  { href: "/admin/appointments",   label: "Записи",              icon: "briefcase",  roles: ["admin", "moderator"] },
  { href: "/admin/content",        label: "Контент сайту",       icon: "file",       roles: ["admin"] },
  { href: "/admin/me",             label: "Мiй кабiнет",         icon: "user",     roles: ["member"] },
  { href: "/admin/emails",         label: "Пошта (Inbox)",       icon: "inbox",    roles: ["admin", "moderator"] },
  { href: "/admin/chat",           label: "Внутрішній Чат",      icon: "user",     roles: ["admin", "moderator"] },
  { href: "/admin/projects",       label: "Agile Проекти",       icon: "clipboard",roles: ["admin", "moderator"] },
  { href: "/admin/products",       label: "Товари & Склад",      icon: "briefcase",roles: ["admin", "moderator"] },
  { href: "/admin/orders",         label: "Замовлення",          icon: "cash",     roles: ["admin", "moderator"] },
  { href: "/admin/lms",            label: "Академія (LMS)",      icon: "book",     roles: ["admin", "moderator"] },
  { href: "/admin/knowledge",      label: "База Знань & AI",     icon: "target",   roles: ["admin", "moderator"] },
  { href: "/admin/secure-links",   label: "Захищені Посилання",  icon: "link",     roles: ["admin"] },
  { href: "/admin/extensions",     label: "Плагіни (Marketplace)",icon: "grid",     roles: ["admin"] },
  { href: "/admin/api-keys",       label: "API & Webhooks",      icon: "key",      roles: ["admin"] },
  { href: "/admin/initiatives",    label: "Соціальні Проекти",   icon: "heart",    roles: ["admin", "moderator"] },
  { href: "/admin/automations",    label: "Автоматизація ⚡",     icon: "zap",      roles: ["admin"] },
  { href: "/admin/monitoring",     label: "Моніторинг",          icon: "alert",    roles: ["admin"] },
  { href: "/admin/audit",          label: "Журнал Аудиту",       icon: "file",     roles: ["admin"] },
  { href: "/admin/settings",       label: "Налаштування",        icon: "settings", roles: ["admin"] },
];

export function navFor(role) {
  return NAV.filter((n) => n.roles.includes(role));
}

const PERMS = {
  "members.write": ["admin", "moderator"],
  "members.delete": ["admin"],
  "leads.write": ["admin", "moderator"],
  "content.write": ["admin"],
  "settings": ["admin"],
};

export function can(role, action) {
  return (PERMS[action] || []).includes(role);
}
